inputs:
  SITE_NAME:
    required: true
  SECRETS_JSON:
    required: true
  VERCEL_TOKEN:
    required: true
  VERCEL_ORG_ID:
    required: true
  VERCEL_PROJECT_ID:
    required: true





runs: 
  using: "composite"
  steps:
  - name: checkout
    id: checkout
    uses: actions/checkout@v2

  - name: DeploySetEnv   
    uses: coopTilleuls/action-deploy-set-env@v1
    id: deploy_set_env
    with:
      SITE_NAME: ${{ inputs.SITE_NAME }}
      SECRETS_JSON: ${{ inputs.SECRETS_JSON }}
    
  - name: VercelDeploy 
    id: VercelDeploy
    uses: amondnet/vercel-action@v25.1.0
    with:
      # token github_action_les_tilleuls_coop sur compte de Julien, via https://vercel.com/account/tokens
      vercel-token: ${{ inputs.VERCEL_TOKEN }}
      # Optional:
      #github-token: ${{ inputs.GITHUB_TOKEN }}
      #vercel-args: '--prod' #Optional
      vercel-args: ${{ steps.deploy_set_env.outputs.VERCEL_ARGS }}
      # org id : https://vercel.com/teams/tilleuls/settings (team id)
      vercel-org-id: ${{ inputs.VERCEL_ORG_ID}}
      # project id : https://vercel.com/tilleuls/les-tilleuls-website/settings
      vercel-project-id: ${{ inputs.VERCEL_PROJECT_ID}}
      #working-directory: ./frontend # already in vercel config
      scope: ${{ inputs.VERCEL_ORG_ID}}
      alias-domains: ${{ steps.deploy_set_env.outputs.SITE_FRONT_VERCEL_DOMAIN }}
