runs: 
using: "composite"
  steps:
  - name: checkout
    id: checkout
    uses: actions/checkout@v2

  - name: DeploySetEnv   
    uses: coopTilleuls/action-deploy-set-env@v1
    id: deploy_set_env
    with:
      SITE_NAME: ${{ secrets.SITE_NAME }}
      SECRETS_JSON: ${{ toJSON(secrets) }}
    
  - name: VercelDeploy 
    id: VercelDeploy
    uses: amondnet/vercel-action@v20
    with:
      # token github_action_les_tilleuls_coop sur compte de Julien, via https://vercel.com/account/tokens
      vercel-token: ${{ secrets.VERCEL_TOKEN }}
      # Optional:
      #github-token: ${{ secrets.GITHUB_TOKEN }}
      #vercel-args: '--prod' #Optional
      vercel-args: '${{ steps.deploy_set_env.outputs.VERCEL_ARGS }}'
      # org id : https://vercel.com/teams/tilleuls/settings (team id)
      vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
      # project id : https://vercel.com/tilleuls/les-tilleuls-website/settings
      vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
      #working-directory: ./frontend # already in vercel config
      scope: ${{ secrets.VERCEL_ORG_ID}}
      alias-domains: |
        ${{ steps.deploy_set_env.outputs.SITE_FRONT_VERCEL_DOMAIN }}
